version: '3'
services:
  mongodb:
    image: mongo
    command: mongod
    ports:
      - 27017:27017
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  mongo_seed:
    image: mongo
    volumes:
      - ./data.json:/data.json
    links:
      - mongodb
    command: mongoimport --host mongodb --db seconddrivedb --collection warehouses --type json --file data.json --jsonArray
  
networks:
  backend:
  frontend: